In [1]:
import math

import numpy as np
import matplotlib.pyplot as plt

import openrtdynamics2.lang as dy
from openrtdynamics2.ORTDtoNumpy import ORTDtoNumpy

from helper_fn import * 

In [2]:

@ORTDtoNumpy()
def test_fn1( a, b ):
    
    c = a + b
    d = a * b
    
    return c, d


@ORTDtoNumpy()
def test_fn2( a, b ):
    
    c = a + b
    
    return c


@ORTDtoNumpy()
def test_fn3( u ):
    
    y = dy.dtf_lowpass_1_order(u, 0.6)
    
    return y

@ORTDtoNumpy(p=2)
def test_fn4( a, b, c : dy.SignalUserTemplate, d : dy.SignalUserTemplate, p ):
    
    r = a + 10*b + 100*c + 1000*d + 10000*p
    
    return r


In [3]:
c, d = test_fn1(1.5, 2.5)
assert c == 4
assert d == 3.75
print(c, d)

compiling system simulation (level 0)... 
determine_execution_order on level 0
--- signals needed for output_1 --
-> S input_1
.    --> crosses system bounds
.  added input dependency input_1 (double [1])
-> S input_2
.    --> crosses system bounds
.  added input dependency input_2 (double [1])
added output_1 (double [1]) type proposal: (double [1])
determine_execution_order on level 1
--- signals needed for output_2 --
-> S input_1
.  has already been calculated in a previous traversion
.  as it is also a simulation input, adding it to the list of depended inputs
-> S input_2
.  has already been calculated in a previous traversion
.  as it is also a simulation input, adding it to the list of depended inputs
added output_2 (double [1]) type proposal: (double [1])
[4.] [3.75]


In [4]:
c = test_fn2(1.5, 2.5)
assert c == 4

c = test_fn2(1.5, 2.5)
assert c == 4

c = test_fn2(1.5, 2.5)
assert c == 4

c

compiling system simulation (level 0)... 
determine_execution_order on level 0
--- signals needed for output_1 --
-> S input_1
.    --> crosses system bounds
.  added input dependency input_1 (double [1])
-> S input_2
.    --> crosses system bounds
.  added input dependency input_2 (double [1])
added output_1 (double [1]) type proposal: (double [1])


array([4.])

In [5]:
y = test_fn3( np.ones(10) )
y

compiling system simulation (level 0)... 
determine_execution_order on level 0
--- signals needed for output_1 --
-> S s5
.  --- signals needed for s5 --
.  -> S s2
.  .  --- signals needed for s2 --
.  .    (no signals needed) 
.  .  added s2 (double [1])
.  -> S s8
.  .  --- signals needed *indirectly* to compute s8 (through state update) --
.  .  -> S output_1
.  .  --- signals needed for s8 --
.  .    (no signals needed) 
.  .  added s8 (double [1]) type proposal: (double [1])
.  added s5 (double [1]) type proposal: (double [1])
-> S s6
.  --- signals needed for s6 --
.  -> S s4
.  .  --- signals needed for s4 --
.  .  -> S s3
.  .  .  --- signals needed for s3 --
.  .  .    (no signals needed) 
.  .  .  added s3 (double [1])
.  .  -> S s2
.  .  .  has already been calculated in this traversion
.  .  added s4 (double [1]) type proposal: (double [1])
.  -> S input_1
.  .    --> crosses system bounds
.  .  added input dependency input_1 (double [1])
.  added s6 (double [1]) type prop

array([0.4       , 0.64      , 0.784     , 0.8704    , 0.92224   ,
       0.953344  , 0.9720064 , 0.98320384, 0.9899223 , 0.99395338])

In [6]:
assert_approx( y , [0.4       , 0.64      , 0.784     , 0.8704    , 0.92224   ,
       0.953344  , 0.9720064 , 0.98320384, 0.9899223 , 0.99395338] )

In [7]:
y = test_fn4(1, 2, c=3, d=4)
assert y == 24321
y

compiling system simulation (level 0)... 
determine_execution_order on level 0
--- signals needed for output_1 --
-> S s13
.  --- signals needed for s13 --
.  -> S s10
.  .  --- signals needed for s10 --
.  .  -> S s7
.  .  .  --- signals needed for s7 --
.  .  .  -> S input_1
.  .  .  .    --> crosses system bounds
.  .  .  .  added input dependency input_1 (double [1])
.  .  .  -> S s6
.  .  .  .  --- signals needed for s6 --
.  .  .  .  -> S input_2
.  .  .  .  .    --> crosses system bounds
.  .  .  .  .  added input dependency input_2 (double [1])
.  .  .  .  -> S s5
.  .  .  .  .  --- signals needed for s5 --
.  .  .  .  .    (no signals needed) 
.  .  .  .  .  added s5 (int32_t [1])
.  .  .  .  added s6 (double [1]) type proposal: (double [1])
.  .  .  added s7 (double [1]) type proposal: (double [1])
.  .  -> S s9
.  .  .  --- signals needed for s9 --
.  .  .  -> S c
.  .  .  .    --> crosses system bounds
.  .  .  .  added input dependency c (double [1])
.  .  .  -> S s8
.  . 

array([24321.])

In [8]:
test_fn4(1, 2, d=4, c=3)
assert y == 24321
y

array([24321.])

In [9]:
passed = False
try:
    # this shall throw because one position based argument is missing
    test_fn4(1, d=4, c=3)
except:
    passed = True
    
assert passed