In [1]:
import math
import numpy as np
import openrtdynamics2.lang as dy
import openrtdynamics2.py_execute as dyexe

from helper_fn import * 

In [2]:
system = dy.enter_system()

# the diagram
activation_sample = dy.system_input( dy.DataTypeFloat64(1), name='activation_sample', default_value=5 ,  value_range=[0, 100], title="input #1")

activate_subsystem = dy.logic_and( dy.counter() >= activation_sample, (dy.counter()-15) < activation_sample )

with dy.sub_if(activate_subsystem, prevent_output_computation=False ) as system:

    cnt = dy.counter()
    
    system.set_outputs([ cnt ])

cnt = system.outputs[0]

# define output(s)
dy.append_primay_ouput(cnt, 'cnt')
dy.append_primay_ouput(activate_subsystem, 'activate_subsystem')

# generate code for Web Assembly (wasm), requires emcc (emscripten) to build
code_gen_results = dy.generate_code(template=dy.WasmRuntime(), folder="generated/sub_if", build=False)

#
dy.clear()

compiling system Subsystem1000 (level 1)... 
determining the computation order...
building execution paths...
All dependencies are resolved.
compiling system simulation (level 0)... 
determining the computation order...
building execution paths...
All dependencies are resolved.
Generated code will be written to generated/sub_if .


In [3]:
compiled_system = dyexe.CompiledCode(code_gen_results)
sim_results = dyexe.run_batch_simulation(dyexe.SystemInstance(compiled_system), input_data={}, N=30)

In [4]:
sim_results['cnt']

array([ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,
        8.,  9., 10., 11., 12., 13., 14., 15., 15., 15., 15., 15., 15.,
       15., 15., 15., 15.])

In [5]:
assert_equal( sim_results['cnt'] , [0.,  0.,  0.,  0.,  0.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,
        8.,  9., 10., 11., 12., 13., 14., 15., 15., 15., 15., 15., 15.,
       15., 15., 15., 15.] )

In [6]:
sim_results['activate_subsystem']

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
system = dy.enter_system()

# the diagram
activation_sample = dy.system_input( dy.DataTypeFloat64(1), name='activation_sample', default_value=5 ,  value_range=[0, 100], title="input #1")

activate_subsystem = dy.logic_and( dy.counter() >= activation_sample, (dy.counter()-15) < activation_sample )

with dy.sub_if(activate_subsystem, prevent_output_computation=False ) as system:

    cnt1 = dy.sum( 1 )
    cnt2 = dy.sum( 1, no_delay=True )
    cnt3 = dy.sum( 1, no_delay=True, initial_state=-1 )
    cnt4 = dy.euler_integrator( dy.float64(0.1), Ts=1.0, initial_state=dy.float64(-5) )
    
    system.set_outputs([ cnt1, cnt2, cnt3, cnt4 ])

# define output(s)
dy.append_primay_ouput(system.outputs[0], 'cnt1')
dy.append_primay_ouput(system.outputs[1], 'cnt2')
dy.append_primay_ouput(system.outputs[2], 'cnt3')
dy.append_primay_ouput(system.outputs[3], 'cnt4')
dy.append_primay_ouput(activate_subsystem, 'activate_subsystem')

# generate code for Web Assembly (wasm), requires emcc (emscripten) to build
code_gen_results = dy.generate_code(template=dy.WasmRuntime(), folder="generated/sub_if", build=False)

#
dy.clear()

compiling system Subsystem1000 (level 1)... 
determining the computation order...
building execution paths...
All dependencies are resolved.
compiling system simulation (level 0)... 
determining the computation order...
building execution paths...
All dependencies are resolved.
Generated code will be written to generated/sub_if .


In [8]:
compiled_system = dyexe.CompiledCode(code_gen_results)
sim_results = dyexe.run_batch_simulation(dyexe.SystemInstance(compiled_system), input_data={}, N=30)

In [9]:
sim_results['cnt1']

array([ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,
        8.,  9., 10., 11., 12., 13., 14., 15., 15., 15., 15., 15., 15.,
       15., 15., 15., 15.])

In [10]:
sim_results['cnt2']

array([ 1.,  1.,  1.,  1.,  1.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,
        9., 10., 11., 12., 13., 14., 15., 16., 16., 16., 16., 16., 16.,
       16., 16., 16., 16.])

In [11]:
sim_results['cnt3']

array([ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,
        8.,  9., 10., 11., 12., 13., 14., 15., 15., 15., 15., 15., 15.,
       15., 15., 15., 15.])

In [12]:
sim_results['cnt4']

array([-5. , -5. , -5. , -5. , -5. , -5. , -4.9, -4.8, -4.7, -4.6, -4.5,
       -4.4, -4.3, -4.2, -4.1, -4. , -3.9, -3.8, -3.7, -3.6, -3.5, -3.5,
       -3.5, -3.5, -3.5, -3.5, -3.5, -3.5, -3.5, -3.5])

In [13]:
sim_results['activate_subsystem']

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
assert_equal( sim_results['cnt1'] , [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,
        8.,  9., 10., 11., 12., 13., 14., 15., 15., 15., 15., 15., 15.,
       15., 15., 15., 15.] )

In [15]:
assert_equal( sim_results['cnt2'] , [ 1.,  1.,  1.,  1.,  1.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,
        9., 10., 11., 12., 13., 14., 15., 16., 16., 16., 16., 16., 16.,
       16., 16., 16., 16.] )

In [16]:
assert_equal( sim_results['cnt3'] , [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,
        8.,  9., 10., 11., 12., 13., 14., 15., 15., 15., 15., 15., 15.,
       15., 15., 15., 15.] )

In [17]:
system = dy.enter_system()

# the diagram
activation_sample = dy.system_input( dy.DataTypeFloat64(1), name='activation_sample', default_value=5 ,  value_range=[0, 100], title="input #1")

activate_subsystem = dy.logic_and( dy.counter() >= activation_sample, (dy.counter()-15) < activation_sample )

with dy.sub_if(activate_subsystem, prevent_output_computation=True ) as system:

    cnt1 = dy.sum( 1 )
    cnt2 = dy.sum( 1, no_delay=True )
    cnt3 = dy.sum( 1, no_delay=True, initial_state=-1 )
    cnt4 = dy.euler_integrator( dy.float64(0.1), Ts=1.0, initial_state=dy.float64(-5) )
    
    system.set_outputs([ cnt1, cnt2, cnt3, cnt4 ])

# define output(s)
dy.append_primay_ouput(system.outputs[0], 'cnt1')
dy.append_primay_ouput(system.outputs[1], 'cnt2')
dy.append_primay_ouput(system.outputs[2], 'cnt3')
dy.append_primay_ouput(system.outputs[3], 'cnt4')
dy.append_primay_ouput(activate_subsystem, 'activate_subsystem')

# generate code for Web Assembly (wasm), requires emcc (emscripten) to build
code_gen_results = dy.generate_code(template=dy.WasmRuntime(), folder="generated/sub_if", build=False)

#
dy.clear()

compiling system Subsystem1000 (level 1)... 
determining the computation order...
building execution paths...
All dependencies are resolved.
compiling system simulation (level 0)... 
determining the computation order...
building execution paths...
All dependencies are resolved.
Generated code will be written to generated/sub_if .


In [18]:
compiled_system = dyexe.CompiledCode(code_gen_results)
sim_results = dyexe.run_batch_simulation(dyexe.SystemInstance(compiled_system), input_data={}, N=30)

Note: because 'prevent_output_computation=True' the output samples of the signals 'cntX' are undefined when the if-subsystem is not active (activate_subsystem=false)

In [19]:
sim_results['cnt1'][5:]

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 14., 14., 14., 14., 14., 14., 14., 14., 14., 14.])

In [20]:
sim_results['cnt2'][5:]

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.])

In [21]:
sim_results['cnt3'][5:]

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 14., 14., 14., 14., 14., 14., 14., 14., 14., 14.])

In [22]:
sim_results['cnt4'][5:]

array([-5. , -4.9, -4.8, -4.7, -4.6, -4.5, -4.4, -4.3, -4.2, -4.1, -4. ,
       -3.9, -3.8, -3.7, -3.6, -3.6, -3.6, -3.6, -3.6, -3.6, -3.6, -3.6,
       -3.6, -3.6, -3.6])

In [23]:
sim_results['activate_subsystem']

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
assert_equal( sim_results['cnt1'][5:] , [  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 14., 14., 14., 14., 14., 14., 14., 14., 14., 14.  ] )

In [25]:
assert_equal( sim_results['cnt2'][5:] , [  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.  ] )

In [26]:
assert_equal( sim_results['cnt3'][5:] , [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 14., 14., 14., 14., 14., 14., 14., 14., 14., 14.   ] )

In [27]:
system = dy.enter_system()

# the diagram
activation_sample    = dy.system_input( dy.DataTypeFloat64(1), name='activation_sample', default_value=10 ,  value_range=[0, 100], title="input #1")
osc_excitement       = dy.system_input( dy.DataTypeFloat64(1), name='osc_excitement',    default_value=0.5,  value_range=[0, 4.0], title="input #2")


activate_subsystem = dy.logic_and( dy.counter() >= activation_sample, (dy.counter()-100) < activation_sample )

with dy.sub_if(activate_subsystem, prevent_output_computation=False ) as system:

    x = dy.signal()
    v = dy.signal()

    acc = dy.add( [ osc_excitement, v, x ], [ 1, -0.1, -0.1 ] ).set_blockname('acc').set_name('acc')

    v << dy.euler_integrator( acc, Ts=0.1, initial_state=-1.0 )
    x << dy.euler_integrator( v, Ts=0.01, initial_state=0.123 )
    
    v.set_name('v')
    x.set_name('x')

    system.set_outputs([ x, v ])

output_x = system.outputs[0]
output_v = system.outputs[1]



# define output(s)
dy.append_primay_ouput(output_x, 'output_x')
dy.append_primay_ouput(output_v, 'output_v')
dy.append_primay_ouput(activate_subsystem, 'activate_subsystem')



# generate code for Web Assembly (wasm), requires emcc (emscripten) to build
code_gen_results = dy.generate_code(template=dy.WasmRuntime(), folder="generated/sub_if", build=False)

#
dy.clear()

compiling system Subsystem1000 (level 1)... 
determining the computation order...
building execution paths...
All dependencies are resolved.
compiling system simulation (level 0)... 
determining the computation order...
building execution paths...
All dependencies are resolved.
Generated code will be written to generated/sub_if .


In [28]:
compiled_system = dyexe.CompiledCode(code_gen_results)
sim_results = dyexe.run_batch_simulation(dyexe.SystemInstance(compiled_system), input_data={}, N=120)

Tests

In [29]:
sim_results['output_x']

array([0.123     , 0.123     , 0.123     , 0.123     , 0.123     ,
       0.123     , 0.123     , 0.123     , 0.123     , 0.123     ,
       0.123     , 0.113     , 0.1035877 , 0.09475822, 0.08650668,
       0.07882818, 0.07171781, 0.06517067, 0.05918182, 0.05374635,
       0.04885931, 0.04451576, 0.04071077, 0.03743938, 0.03469662,
       0.03247756, 0.03077721, 0.02959062, 0.02891281, 0.02873883,
       0.02906369, 0.02988243, 0.03119008, 0.03298166, 0.03525221,
       0.03799676, 0.04121033, 0.04488797, 0.04902471, 0.05361559,
       0.05865567, 0.06413998, 0.07006358, 0.07642153, 0.0832089 ,
       0.09042075, 0.09805216, 0.10609822, 0.11455401, 0.12341463,
       0.13267519, 0.1423308 , 0.15237659, 0.16280769, 0.17361924,
       0.18480639, 0.19636431, 0.20828817, 0.22057316, 0.23321446,
       0.2462073 , 0.25954689, 0.27322846, 0.28724726, 0.30159854,
       0.3162776 , 0.3312797 , 0.34660015, 0.36223427, 0.37817738,
       0.39442485, 0.41097202, 0.42781428, 0.44494701, 0.46236

In [30]:
sim_results['activate_subsystem']

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])