In [1]:
import math
import numpy as np
import openrtdynamics2.lang as dy
import openrtdynamics2.py_execute as dyexe

from helper_fn import * 

In [2]:
system = dy.enter_system()

# the diagram
output1 = 10 + dy.counter()
output2 = dy.counter() + 20

output3 = 10 - dy.counter()
output4 = dy.counter() - 10

output5 = 2 * dy.counter()
output6 = dy.counter() * 3

output7 = 1.0 / (dy.counter() + 1)
output8 = dy.counter() / 2.0        # NOTE: without .0 this will result in a integer division: TODO: change this in the implementation of the /-operator

# <, >, ==, ...
output9 = 2 == dy.counter()
output10 = dy.counter() == 3

output11 = 2 > dy.counter()
output12 = dy.counter() > 5


# define output(s)
dy.append_output(output1, 'output1')
dy.append_output(output2, 'output2')
dy.append_output(output3, 'output3')
dy.append_output(output4, 'output4')
dy.append_output(output5, 'output5')
dy.append_output(output6, 'output6')
dy.append_output(output7, 'output7')
dy.append_output(output8, 'output8')

dy.append_output(output9, 'output9')
dy.append_output(output10, 'output10')
dy.append_output(output11, 'output11')
dy.append_output(output12, 'output12')


# generate code for Web Assembly (wasm), requires emcc (emscripten) to build
code_gen_results = dy.generate_code(template=dy.TargetWasm(), folder="generated/operators", build=False)

#
dy.clear()

compiling system simulation (level 0)... 
determining the computation order...
building execution paths...
All dependencies are resolved.
Generated code will be written to generated/operators .


In [3]:
compiled_system = dyexe.CompiledCode(code_gen_results)
testsim = dyexe.SystemInstance(compiled_system)

In [4]:
sim_results = dyexe.run_batch_simulation(testsim, input_data={}, N=10)

Tests

In [5]:
sim_results['output1']

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [6]:
assert_equal( sim_results['output1'] , [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.] )

In [7]:
sim_results['output2']

array([20., 21., 22., 23., 24., 25., 26., 27., 28., 29.])

In [8]:
assert_equal( sim_results['output2'] ,[20., 21., 22., 23., 24., 25., 26., 27., 28., 29.] )

In [9]:
sim_results['output3']

array([10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.])

In [10]:
assert_equal( sim_results['output3'] , [10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.] )

In [11]:
sim_results['output4']

array([-10.,  -9.,  -8.,  -7.,  -6.,  -5.,  -4.,  -3.,  -2.,  -1.])

In [12]:
assert_equal( sim_results['output4'] , [-10.,  -9.,  -8.,  -7.,  -6.,  -5.,  -4.,  -3.,  -2.,  -1.] )

In [13]:
sim_results['output5']

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [14]:
assert_equal( sim_results['output5'] , [ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.] )

In [15]:
sim_results['output6']

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [16]:
assert_equal( sim_results['output6'] , [ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [17]:
sim_results['output7']

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [18]:
assert_approx(  sim_results['output7'], [1., 0.5 , 0.33333333, 0.25 , 0.2 ,0.16666667, 0.14285714, 0.125 , 0.11111111, 0.1 ] )

In [19]:
sim_results['output8']

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [20]:
assert_equal( sim_results['output8'] , [  0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5  ])

In [21]:
sim_results['output9']

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
assert_equal( sim_results['output9'] , [  0., 0., 1., 0., 0., 0., 0., 0., 0., 0. ])

In [23]:
sim_results['output10']

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

In [24]:
assert_equal( sim_results['output10'] , [  [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.] ])

In [25]:
sim_results['output11']

array([1., 1., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
assert_equal( sim_results['output11'] , [  1., 1., 0., 0., 0., 0., 0., 0., 0., 0. ])

In [27]:
sim_results['output12']

array([0., 0., 0., 0., 0., 0., 1., 1., 1., 1.])

In [28]:
assert_equal( sim_results['output12'] , [ 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.  ])

In [29]:
# assert_equal( sim_results['output9'] , [   ])

In [30]:
# assert_equal( sim_results['output9'] , [   ])

In [31]:
# assert_equal( sim_results['output9'] , [   ])

In [32]:
# assert_equal( sim_results['output9'] , [   ])

In [33]:
# assert_equal( sim_results['output9'] , [   ])

In [34]:
# assert_equal( sim_results['output9'] , [   ])

In [35]:
# assert_equal( sim_results['output9'] , [   ])

In [36]:
# assert_equal( sim_results['output9'] , [   ])