In [1]:
import math
import numpy as np
import openrtdynamics2.lang as dy
import openrtdynamics2.py_execute as dyexe

from helper_fn import * 

In [2]:
system = dy.enter_system()

# the diagram
s1 = dy.signal_periodic_impulse(period=5, phase=0)
s2 = dy.signal_periodic_impulse(period=4, phase=1)
s3 = dy.signal_periodic_impulse(period=4, phase=2)


# define output(s)
dy.append_primay_ouput(s1, 'signal1')
dy.append_primay_ouput(s2, 'signal2')
dy.append_primay_ouput(s3, 'signal3')


# generate code for Web Assembly (wasm), requires emcc (emscripten) to build
code_gen_results = dy.generate_code(template=dy.WasmRuntime(), folder="generated/sub_signal_periodic_impulse", build=False)

#
dy.clear()

compiling system simulation (level 0)... 
determining the computation order...
building execution paths...
All dependencies are resolved.
Generated code will be written to generated/sub_signal_periodic_impulse .


In [3]:
compiled_system = dyexe.CompiledCode(code_gen_results)
sim_results = dyexe.run_batch_simulation(dyexe.SystemInstance(compiled_system), input_data={}, N=30)

In [4]:
sim_results['signal1']

array([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [5]:
sim_results['signal2']

array([0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1.])

In [6]:
sim_results['signal3']

array([0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.])

In [7]:
assert_equal( sim_results['signal1'] , [ [1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.]  ] )

In [8]:
assert_equal( sim_results['signal2'] , [   0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1.   ] )

In [9]:
assert_equal( sim_results['signal3'] , [ [0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.]  ] )